---
nginx/pcre-8.39.tar.gz:
  object_id: id0
  sha: sha0
  size: 1
awscli/awscli-bundle-1.11.21.zip:
  object_id: id1
  sha: sha1
  size: 2
nginx/newrelic_nginx_agent-1.2.1.tar.gz:
  object_id: id2
  sha: sha2
  size: 3
