---
nginx/pcre-8.39.tar.gz:
  object_id: id0
  sha: sha0
  size: 1
awscli/awscli-bundle-1.11.21.zip:
  object_id: id1
  sha: sha1
  size: 2
erlang/otp_src_oss_18.3.4.4.tgz:
  object_id: id2
  sha: sha2
  size: 3
