---
nginx/pcre-8.39.tar.gz:
  object_id: id0
  sha: sha0
  size: 1
nginx/newrelic_nginx_agent-test.tar.gz:
  object_id: id2
  sha: sha2
  size: 3
app-autoscaler/cf-autoscaling:
  object_id: id3
  sha: sha3
  size: 4
